# Generated by Django 2.2.3 on 2020-12-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classblog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classblog',
            name='updated_at',
        ),
    ]
